---
- name: Install/Update Application Dynamics Java Server Agent
  hosts: all

  vars_files:
    - vars.yml

  tasks:
  - name: "Create Appd apache agent home directory {{ appd_apacheagent_home }} that will be owned by {{ appd_user }}" 
    file:
      path: "{{ appd_apacheagent_home }}"
      state: directory
      mode: 0775
      owner: "{{ appd_user }}"
      group: "{{ appd_user }}"
    become: yes
    become_user: "{{ appd_user }}"      

  - name: "Unarchive AppD Apache agent from {{ appd_apache_source }} to {{ appd_apacheagent_home }}"
    unarchive:
      src: "{{ appd_apache_source }}"
      dest: "{{ appd_apacheagent_home }}"
      creates: "{{ appd_apacheagent_home }}/appdynamics-sdk-native"
      owner: "{{ appd_user }}"
      group: "{{ appd_user }}"
    become: yes
    become_user: "{{ appd_user }}"     

## Create a new appd agent config file for each node
  - name: "Process template for {{apache_nodes.config_file}}"
    template:
     src: "{{ appd_agent_config_template }}"
     dest: "{{ appd_agent_config_file }}"
     owner: "{{ appd_user }}"
     group: "{{ appd_user }}"
     mode: 0644
     force: yes
     backup: yes

  - name: "Add the Include directive to {{ appd_apache_conf_file }}"
    become: yes
    become_user: "{{ appd_user }}"  
    lineinfile:
      path: "{{appd_apache_conf_dir }}/{{ item.config_file }}"
      line: "Include /app/httpd/conf/extra/appdynamics_agent.conf"
      regex: ^\s*Include\s* /app/httpd/conf/extra/appdynamics_agent.conf
      state: present
      insertafter: ^BrowserMatch\s*.*redirect-carefully$
      backup: yes 
    with_items: "{{ apache_nodes }}"   

  - name: "Add AppDynamicsApplicationContext to virtual server configuration for {{ apache_nodes.virt_server }}"
    become: yes
    become_user: "{{ appd_user }}"
    lineinfile:
      path: "{{appd_apache_conf_dir }}/{{ item.config_file }}"
      line: " AppDynamicsApplicationContext {{ item.app }} {{ item.node }} {{inventory_hostname}}"
      insertafter: ^.*((S|s)erver(N|n)ame|(S|s)erver(A|a)lias)\s* {{ item.virt_server }}.*$
      state: present
    with_items: "{{ apache_nodes }}"

  - name: "Run appd {{ appd_apacheagent_home }}/appdynamics-sdk-native/install.sh - ignore all errors"  
    become_user: "{{ appd_user }}"
    shell: "{{ appd_apacheagent_home }}/appdynamics-sdk-native/install.sh"
    ignore_errors: yes

  - name: "Get proxy server process PID if it is running"
    become_user: "{{ appd_user }}" 
    shell: pgrep runSDKProxy
    ignore_errors: yes
    changed_when: false
    register: proxy_procs

  - name: "Stop local appd proxy {{ appd_proxy_restart_cmd }}"
    become: yes
    become_user: "{{ appd_user }}" 
    shell: "kill {{ proxy_procs.stdout }}"
    when: proxy_procs.stdout != "" 
  
  - name: "Start local appd proxy {{ appd_proxy_restart_cmd }}"
    become: yes
    become_user: "{{ appd_user }}"
    shell: "{{ appd_proxy_restart_cmd }}"        
