ungrouped:
  hosts:
    itwwwedev01: # Template system
      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
      ansible_ssh_user: httpd    
      apache_nodes: 
      - {config_file: 'httpd-cda.conf', virt_server: 'itwwwedev01g', app: 'ShareMyData_Dev', node: 'itwwwedev01g'}
      - {config_file: 'httpd-cda.conf', virt_server: 'sharemydatadev', app: 'ShareMyData_Dev', node: 'sharemydatadev'}
      - {config_file: 'httpd-www3.conf', virt_server: 'sharemydatadev3', app: 'ShareMyData_Dev', node: 'itwwwedev01f'}
      - {config_file: 'httpd-www4.conf', virt_server: 'sharemydatadev2', app: 'ShareMyData_Dev', node: 'sharemydatadev2'}
      

#  itwwwdev01: # This host is using Python 2.4 and does not work. Needs to be upgraded
#      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
#      appd_application_name: ShareMyData_Dev
#      ansible_ssh_user: httpd
#      apache_nodes: 
#      - {node: 'mye', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}

apache_hosts:
  hosts:
    itwwwedev01: 

test_host:
  hosts:
    itwwwedev01: