ungrouped:
  hosts:
    itwwwedev01: # Template system
      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
      ansible_ssh_user: httpd    
      apache_nodes: 
      - {node: 'cda',  appd_node: 'itwwwedev01b',    appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}
      - {node: 'www4', appd_node: 'sharemydatadev2', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}
      - {node: 'www3', appd_node: 'itwwwedev01f',    appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}

    itwwwetst01: # I can't restart httpd
      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
      ansible_ssh_user: httpd  
      apache_nodes: 
      - {node: 'cda',  appd_node:  'sharemydatatest',  appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}
      - {node: 'www3',  appd_node: 'sharemydatatest3', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}
      - {node: 'www4', appd_node:  'sharemydatatest2', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}

    itwwwdev01: # This host is using Python 2.4 and does not work. Needs to be upgraded
      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
      appd_application_name: ShareMyData_Dev
      ansible_ssh_user: httpd
      apache_nodes: 
      - {node: 'mye', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}

    ccwwwetst01: # The destination directory (/etc/httpd/conf) is not writable
      ansible_ssh_private_key_file: /home/weblogic/.ssh/jenkins_id_rsa 
      ansible_ssh_user: httpd  
      apache_nodes:
      - {node: 'pge2', appd_app_name: 'ShareMyData_Dev', appd_tier: WebTier}
      

apache_hosts:
  hosts:
    itwwwetst01:
    itwwwedev01: 